// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  React.useEffect(function () {
        
      });
  
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
