// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";

function Index$App(Props) {
  return React.createElement("div", {
              className: "text-4xl max-w-3xl mx-auto bg-gray-300 text-center py-4 mt-36"
            }, "Hello World");
}

var App = {
  make: Index$App
};

var root = document.querySelector("#root");

if (root == null) {
  console.log("Error: could not find react element");
} else {
  ReactDom.render(React.createElement(Index$App, {}), root);
}

if (import.meta.hot) {
  import.meta.hot.accept();
}

export {
  App ,
  
}
/* root Not a pure module */
